using System.Reflection;
using System.Runtime.InteropServices;

// WARNING: If this file is named AssemblyInfo.cs, then it is autogenerated!
//
// Please edit tokenized/AssemblyInfo.cs.in.

[assembly: AssemblyTitle("RabbitMQ.ServiceModel")]
[assembly: AssemblyDescription("RabbitMQ Binding for Windows Communication Foundation With Load Balance. Powered by Lee.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Pivotal Software, Inc.")]
[assembly: AssemblyProduct("RabbitMQ")]
[assembly: AssemblyCopyright("Copyright © 2007-2020 Pivotal Software, Inc.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

// 程序集的版本信息由下面四个值组成: 
//
//      主版本
//      次版本 
//      生成号
//      修订号
//
// 可以指定所有这些值，也可以使用“生成号”和“修订号”的默认值，
// 方法是按如下所示使用“*”: 
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
